# Projeto 5: Classificação binária brest cancer - carregar o classificador

## Etapa 1: Importação das bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import accuracy_score
torch.__version__

'1.4.0'

## Etapa 2: Carregamento do classificador

In [ ]:
np.random.seed(123)
torch.manual_seed(123)

In [ ]:
class classificador_torch(nn.Module):
    def __init__(self):
        super().__init__() 
        self.dense0 = nn.Linear(30, 8)
        torch.nn.init.normal_(self.dense0.weight, mean = 0.0, std = 0.05)
        self.dense1 = nn.Linear(8, 8)
        torch.nn.init.normal_(self.dense1.weight, mean = 0.0, std = 0.05)
        self.dense2 = nn.Linear(8, 1)
        self.activation = nn.ReLU()
        self.dropout = nn.Dropout(0.2)
        self.output = nn.Sigmoid()
        
    def forward(self, X):
        X = self.dense0(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense1(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense2(X)
        X = self.output(X)
        return X

In [ ]:
classificador = classificador_torch()

In [ ]:
state_dict = torch.load('/content/checkpoint.pth')

In [ ]:
state_dict

OrderedDict([('dense0.weight',
              tensor([[-6.2938e-01, -6.3880e-02, -3.8812e-01, -1.0131e-01,  5.3613e-02,
                       -5.2737e-02,  5.9786e-02, -6.1688e-02,  2.9235e-02,  8.3439e-02,
                        5.2364e-04,  1.0153e-03,  6.2318e-04, -1.3868e-03,  1.9200e-02,
                        1.1765e-01, -3.8250e-01, -2.6600e-01, -6.0278e-03,  4.2274e-01,
                       -4.7407e-01, -3.1142e-02, -3.2840e-01,  1.8073e-01,  4.6571e-02,
                        4.2041e-02,  2.2235e-02,  4.5930e-02,  3.1673e-02,  6.3382e-01],
                      [ 8.2934e-02,  1.6680e-02,  5.3591e-02, -5.2363e-02,  8.3542e-02,
                       -2.1720e-04,  4.8437e-02, -1.6592e-03, -7.1113e-02, -2.8021e-02,
                        1.3983e-02, -1.1551e-02, -4.8893e-02,  1.0772e-01, -1.0227e-14,
                        1.0606e-04,  1.7713e-02, -3.5398e-13, -3.3772e-03, -4.1128e-14,
                       -5.3233e-02,  4.5062e-02, -4.9869e-02, -6.6557e-02, -8.3495e-02,


In [ ]:
classificador.load_state_dict(state_dict)

<All keys matched successfully>

## Etapa 3: Previsões


In [ ]:
novo = torch.tensor([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                      0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                      0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                      0.84, 158, 0.363]])

In [ ]:
classificador.eval()
previsao = classificador(novo)
previsao = (previsao.detach().numpy() > 0.5)
previsao

array([[ True]])

In [ ]:
previsores = pd.read_csv('entradas_breast.csv')
classe = pd.read_csv('saidas_breast.csv')

In [ ]:
previsores = torch.tensor(np.array(previsores), dtype = torch.float)
classe = torch.tensor(np.array(classe), dtype = torch.float)

In [ ]:
previsoes = classificador.forward(previsores).detach()

In [ ]:
previsoes

tensor([[3.3619e-09],
        [3.0388e-06],
        [1.5145e-04],
        [3.5191e-06],
        [2.2233e-03],
        [4.7528e-01],
        [1.4093e-06],
        [1.3330e-01],
        [2.5540e-01],
        [1.8320e-03],
        [4.2396e-02],
        [8.5285e-04],
        [9.9829e-02],
        [8.8744e-01],
        [8.8744e-01],
        [3.5808e-01],
        [5.0094e-03],
        [3.0899e-04],
        [4.2117e-11],
        [8.9949e-01],
        [8.8744e-01],
        [1.0000e+00],
        [3.0697e-01],
        [1.4129e-11],
        [1.2917e-11],
        [6.7493e-05],
        [3.5850e-01],
        [5.9922e-03],
        [1.7778e-04],
        [1.0012e-01],
        [1.0845e-04],
        [1.5636e-02],
        [2.1436e-03],
        [1.6318e-06],
        [5.0767e-04],
        [3.2572e-02],
        [8.3584e-01],
        [9.9843e-01],
        [7.8532e-01],
        [5.6025e-01],
        [6.6390e-01],
        [8.8744e-01],
        [4.0306e-06],
        [7.4665e-02],
        [7.9646e-01],
        [1

In [ ]:
F.binary_cross_entropy(previsoes, classe).numpy()

array(0.16732648, dtype=float32)

In [ ]:
accuracy_score(classe.numpy(), (previsoes > 0.5).numpy())

0.9420035149384886