# Projeto 4: Classificação binária brest cancer - classificar somente um registro e salvar o classificador

## Etapa 1: Importação das bibliotecas

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score
import torch
import torch.nn as nn
torch.__version__

'1.4.0'

## Etapa 2: Base de dados

In [ ]:
np.random.seed(123)
torch.manual_seed(123)

In [ ]:
previsores = pd.read_csv('entradas_breast.csv')
classe = pd.read_csv('saidas_breast.csv')

In [ ]:
previsores = torch.tensor(np.array(previsores), dtype = torch.float)
classe = torch.tensor(np.array(classe), dtype = torch.float)

In [ ]:
type(previsores)

torch.Tensor

## Etapa 3: Transformação dos dados para tensores


In [ ]:
train_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(previsores, classe), batch_size = 10, shuffle = True)

## Etapa 4: Construção do modelo

In [ ]:
class classificador_torch(nn.Module):
    def __init__(self):
        super().__init__() 
        self.dense0 = nn.Linear(30, 8)
        # Mesmos parâmetors usados pelo kernel initializer do Keras [https://keras.io/initializers/, ver sessão RandomNormal]
        torch.nn.init.normal_(self.dense0.weight, mean = 0.0, std= 0.05)
        self.dense1 = nn.Linear(8, 8)
        torch.nn.init.normal_(self.dense1.weight, mean = 0.0, std= 0.05)
        self.dense2 = nn.Linear(8, 1)
        self.activation = nn.ReLU()
        self.dropout = nn.Dropout(0.2)
        self.output = nn.Sigmoid()
        
    def forward(self, X):
        X = self.dense0(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense1(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense2(X)
        X = self.output(X)
        return X

In [ ]:
classificador = classificador_torch()

In [ ]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(classificador.parameters(), lr = 0.001, 
                             weight_decay = 0.0001)

## Etapa 5: Treinamento do modelo

In [ ]:
for epoch in range(100):
    running_loss = 0.
    
    for data in train_loader:
        inputs, labels = data
        optimizer.zero_grad()        

        outputs = classificador(inputs)
        loss = criterion(outputs, labels)
        loss.backward()    
        optimizer.step()

        running_loss += loss.item()

    print('Época %3d: perda %.5f' % (epoch+1, running_loss/len(train_loader)))

Época   1: perda 1.50244
Época   2: perda 0.73373
Época   3: perda 0.67770
Época   4: perda 0.58107
Época   5: perda 0.57171
Época   6: perda 0.56428
Época   7: perda 0.53814
Época   8: perda 0.50038
Época   9: perda 0.50480
Época  10: perda 0.49681
Época  11: perda 0.47105
Época  12: perda 0.46919
Época  13: perda 0.46847
Época  14: perda 0.46689
Época  15: perda 0.43371
Época  16: perda 0.41159
Época  17: perda 0.40354
Época  18: perda 0.41222
Época  19: perda 0.39259
Época  20: perda 0.38620
Época  21: perda 0.37312
Época  22: perda 0.35878
Época  23: perda 0.36107
Época  24: perda 0.32681
Época  25: perda 0.33623
Época  26: perda 0.36341
Época  27: perda 0.32568
Época  28: perda 0.32805
Época  29: perda 0.31555
Época  30: perda 0.30389
Época  31: perda 0.31813
Época  32: perda 0.33555
Época  33: perda 0.32136
Época  34: perda 0.31885
Época  35: perda 0.29142
Época  36: perda 0.31004
Época  37: perda 0.30168
Época  38: perda 0.27757
Época  39: perda 0.30899
Época  40: perda 0.26122


## Etapa 6: Classificar somente um registro

In [ ]:
novo = torch.tensor([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                  0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                  0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                  0.84, 158, 0.363]], dtype = torch.float)

In [ ]:
classificador.eval()

classificador_torch(
  (dense0): Linear(in_features=30, out_features=8, bias=True)
  (dense1): Linear(in_features=8, out_features=8, bias=True)
  (dense2): Linear(in_features=8, out_features=1, bias=True)
  (activation): ReLU()
  (dropout): Dropout(p=0.2, inplace=False)
  (output): Sigmoid()
)

In [ ]:
previsao = classificador(novo)

In [ ]:
previsao

tensor([[1.]], grad_fn=<SigmoidBackward>)

In [ ]:
previsao = previsao.detach()

In [ ]:
previsao

tensor([[1.]])

In [ ]:
previsao = previsao.numpy()

In [ ]:
type(previsao)

numpy.ndarray

In [ ]:
previsao

array([[1.]], dtype=float32)

In [ ]:
previsao = (previsao > 0.5)
previsao

array([[ True]])

# Etapa 7: Salvar o classificador

In [ ]:
# Quando salvar, você precisa chamar classificador.state_dict() (com os parêntese no final), 
# ao invés de classificador.state_dict

In [ ]:
classificador.state_dict()

OrderedDict([('dense0.weight',
              tensor([[-6.2938e-01, -6.3880e-02, -3.8812e-01, -1.0131e-01,  5.3613e-02,
                       -5.2737e-02,  5.9786e-02, -6.1688e-02,  2.9235e-02,  8.3439e-02,
                        5.2364e-04,  1.0153e-03,  6.2318e-04, -1.3868e-03,  1.9200e-02,
                        1.1765e-01, -3.8250e-01, -2.6600e-01, -6.0278e-03,  4.2274e-01,
                       -4.7407e-01, -3.1142e-02, -3.2840e-01,  1.8073e-01,  4.6571e-02,
                        4.2041e-02,  2.2235e-02,  4.5930e-02,  3.1673e-02,  6.3382e-01],
                      [ 8.2934e-02,  1.6680e-02,  5.3591e-02, -5.2363e-02,  8.3542e-02,
                       -2.1720e-04,  4.8437e-02, -1.6592e-03, -7.1113e-02, -2.8021e-02,
                        1.3983e-02, -1.1551e-02, -4.8893e-02,  1.0772e-01, -1.0227e-14,
                        1.0606e-04,  1.7713e-02, -3.5398e-13, -3.3772e-03, -4.1128e-14,
                       -5.3233e-02,  4.5062e-02, -4.9869e-02, -6.6557e-02, -8.3495e-02,


In [ ]:
# Para salvar o classificador com a versão 1.5.0 do PyTorch, use o código abaixo

# torch.save(classificador.state_dict(), 'checkpoint.pth')

/usr/local/lib/python3.6/dist-packages/torch/serialization.py:360: UserWarning: Couldn't retrieve source code for container of type classificador_torch. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
