### Boxplot

In [1]:
import pandas as pd
base_credit = pd.read_csv('Arquivos/credit_data.csv')
base_census = pd.read_csv('Arquivos/census.csv')

In [2]:
base_credit

clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[2000 rows x 5 columns]

In [3]:
base_credit.isnull().sum()

clientid    0
income      0
age         3
loan        0
default     0
dtype: int64

In [4]:
base_credit.dropna(inplace=True)

In [5]:
base_credit.isnull().sum()

clientid    0
income      0
age         0
loan        0
default     0
dtype: int64

In [6]:
# Outliers
import plotly.express as px
grafico = px.box(base_credit, y='age')
grafico.show()

In [7]:
outliers_age = base_credit[base_credit['age']<0]
outliers_age

clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

In [8]:
grafico = px.box(base_credit, y='loan')
grafico.show()

In [9]:
outliers_loan = base_credit[base_credit['loan']>13300]
outliers_loan

clientid        income        age          loan  default
1378      1379  69755.320163  44.543682  13766.051239        0
1584      1585  67289.585683  26.727400  13376.797706        1
1801      1802  67802.694456  49.037987  13443.473176        0

### Gráfico de Dispersão

In [10]:
# Income x Age

grafico = px.scatter(x=base_credit['income'], y=base_credit['age'])
grafico.show()

In [11]:
# Income x loan

grafico = px.scatter(x=base_credit['income'], y=base_credit['loan'])
grafico.show()

In [12]:
# Age x Loan

grafico = px.scatter(x=base_credit['age'], y=base_credit['loan'])
grafico.show()

In [13]:
# Age x Final Weight

grafico = px.scatter(x=base_census['age'], y=base_census['final-weight'])
grafico.show()

### PYOD

In [14]:
from pyod.models.knn import KNN

In [15]:
base_credit.head(1)

clientid        income        age         loan  default
0         1  66155.925095  59.017015  8106.532131        0

In [17]:
detector = KNN()
detector.fit(base_credit.iloc[:,1:4])

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [18]:
previsoes = detector.labels_
previsoes

array([0, 0, 0, ..., 0, 0, 1])

In [19]:
import numpy as np
np.unique(previsoes, return_counts=True)

(array([0, 1]), array([1797,  200], dtype=int64))

In [20]:
confianca_previsoes = detector.decision_scores_
confianca_previsoes

array([ 704.78948078,  365.218309  ,  583.2159934 , ...,  395.01466508,
        557.88978241, 1071.5109404 ])

In [21]:
outliers = []
for i in range(len(previsoes)):
    #print(i)
    if previsoes[i] == 1:
        outliers.append(i)

In [23]:
print(outliers)

[4, 24, 28, 31, 35, 75, 87, 92, 101, 102, 108, 112, 125, 154, 157, 160, 162, 183, 215, 217, 231, 234, 272, 279, 289, 294, 301, 321, 322, 332, 339, 343, 347, 357, 358, 372, 391, 399, 401, 402, 411, 418, 419, 424, 446, 447, 449, 451, 477, 485, 486, 502, 505, 520, 528, 530, 532, 545, 570, 596, 630, 643, 660, 694, 707, 713, 734, 745, 762, 764, 839, 848, 875, 877, 882, 898, 924, 927, 930, 937, 942, 943, 949, 972, 974, 987, 989, 993, 996, 999, 1003, 1015, 1022, 1025, 1031, 1033, 1037, 1038, 1047, 1054, 1062, 1080, 1085, 1088, 1089, 1091, 1098, 1099, 1125, 1136, 1137, 1181, 1194, 1197, 1199, 1205, 1207, 1209, 1216, 1219, 1232, 1233, 1236, 1288, 1289, 1300, 1335, 1347, 1348, 1367, 1374, 1375, 1376, 1379, 1382, 1385, 1386, 1393, 1411, 1412, 1414, 1425, 1426, 1432, 1440, 1445, 1451, 1467, 1478, 1489, 1503, 1511, 1513, 1517, 1563, 1579, 1581, 1605, 1607, 1613, 1615, 1623, 1627, 1632, 1645, 1657, 1665, 1669, 1672, 1676, 1678, 1685, 1691, 1702, 1713, 1717, 1724, 1730, 1736, 1749, 1752, 1784, 1798, 

In [24]:
lista_outliers = base_credit.iloc[outliers,:]
lista_outliers

clientid        income        age          loan  default
4            5  66952.688845  18.584336   8770.099235        1
24          25  65301.984029  48.840922   5465.267886        0
29          30  58842.891308  54.510948  10871.186790        0
34          35  57584.973790  36.672021   1728.423755        0
38          39  60921.063104  18.840526    968.836383        0
...        ...           ...        ...           ...      ...
1943      1944  59792.508585  24.187499    660.241453        0
1944      1945  35879.519994  41.072935   5335.403499        0
1957      1958  50458.958203  52.314565   9852.889427        0
1996      1997  69516.127573  23.162104   3503.176156        0
1999      2000  69436.579552  56.152617   7378.833599        0

[200 rows x 5 columns]