### Reconhecimento Facial

In [24]:
from PIL import Image
import numpy as np
import os
import cv2

In [25]:
imagem = 'Arquivos/yalefaces/train/'

In [26]:
def dados_imagem():
    caminhos = [os.path.join('Arquivos/yalefaces/train/', f) for f in os.listdir('Arquivos/yalefaces/train/')]
    faces = []
    ids= []
    for caminho in caminhos:
        imagem = Image.open(caminho).convert('L')
        imagem_np = np.array(imagem,'uint8')
        id = int(os.path.split(caminho)[1].split('.')[0].replace('subject',''))
        ids.append(id)
        faces.append(imagem_np)
    return np.array(ids), faces

In [27]:
ids, faces = dados_imagem()

In [28]:
print(ids)

[ 1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  3  3  3  3  3  3
  3  3  3  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5  6  6  6
  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  8  8  8  8  8  8  8  8  8
  9  9  9  9  9  9  9  9  9 10 10 10 10 10 10 10 10 10 11 11 11 11 11 11
 11 11 11 12 12 12 12 12 12 12 12 12 13 13 13 13 13 13 13 13 13 14 14 14
 14 14 14 14 14 14 15 15 15 15 15 15 15 15 15]


In [29]:
print(faces)

[array([[130, 130, 130, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 252, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8), array([[130, 130, 130, ..., 216, 224, 244],
       [255, 255, 255, ..., 215, 220, 245],
       [255, 255, 255, ..., 231, 211, 231],
       ...,
       [255, 255, 255, ..., 192, 197, 203],
       [255, 255, 255, ..., 189, 207, 215],
       [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8), array([[130, 130, 130, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8), array([[130, 130, 130, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 

In [30]:
lbph = cv2.face.LBPHFaceRecognizer_create()
lbph.train(faces,ids)
lbph.write('classificadorLBPG.yml')

#### Classificação

In [31]:
reconhecedor = cv2.face.LBPHFaceRecognizer_create()
reconhecedor.read('classificadorLBPG.yml')

In [49]:
imagem_teste = 'Arquivos/yalefaces/test/subject10.sad.gif'

In [50]:
imagem = Image.open(imagem_teste).convert('L')
imagem_np = np.array(imagem,'uint8')
print(imagem_np)

[[130 130 130 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 241 255 255]
 [255 255 255 ... 234 237 252]
 [ 68  68  68 ...  68  68  68]]


In [42]:
idprevisto, _ = reconhecedor.predict(imagem_np)
idprevisto

10

In [43]:
idcorreto = id = int(os.path.split(imagem_teste)[1].split('.')[0].replace('subject',''))
idcorreto

10

In [51]:
cv2.putText(imagem_np, 'P: '+ str(idprevisto), (10,40), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0))
cv2.putText(imagem_np, 'C: '+ str(idprevisto), (10,70), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0))
cv2.imshow('',imagem_np)
cv2.waitKey()

-1